# Generated by Django 3.0.4 on 2020-03-25 05:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2020, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2020, 1, 1)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=140)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Insta.Post')),
            ],
        ),
    ]
