# Generated by Django 3.0.4 on 2020-04-03 19:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0003_auto_20200324_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/posts'),
        ),
    ]
